### ISSUE TITLE
Its not working on FW 1.0.0

### ISSUE THREAD

**Issue by HommerJr** [shchmue/Lockpick#6]
Its not working on FW 1.0.0. My file "fuses.bin" and "tsec_keys.bin" have been dumped with Hekate 4.6, but lockpick crash every time.

**Comment by shchmue** [comment]
What sort of crash - are there any errors? What CFW are you running? I recommend trying Atmosphere 0.8.2 at least to test.

**Comment by RKX1209** [comment]
Hi. On my environment, FW 5.3.1, it also doesn't work because a size of dumped TSEC key "tsec_keys.bin" is 32 byte. 
I've already confirmed that Lockpick failed at [that point](https://github.com/shchmue/Lockpick/blob/master/source/Common.cpp#L188) due to size mismatch.
In my understanding, TSEC key itself is [16 byte](https://switchbrew.org/wiki/TSEC_Firmware#TSEC_key_generation). Actually my TSEC key displayed on screen is 16 byte, and corresponding to the content of "tsec_keys.bin".
But 16 byte latter half of tsec_keys.bin are all 0.

So my question is what does the 16 byte latter half of tsec_keys.bin indicate? 
What does Lockpick do by "tsec_root.find_key(temp_key)"?

**Comment by shchmue** [comment]
> Hi. On my environment, FW 5.3.1, it also doesn't work because a size of dumped TSEC key "tsec_keys.bin" is 32 byte.
> I've already confirmed that Lockpick failed at [that point](https://github.com/shchmue/Lockpick/blob/master/source/Common.cpp#L188) due to size mismatch.
> In my understanding, TSEC key itself is [16 byte](https://switchbrew.org/wiki/TSEC_Firmware#TSEC_key_generation). Actually my TSEC key displayed on screen is 16 byte, and corresponding to the content of "tsec_keys.bin".
> But 16 byte latter half of tsec_keys.bin are all 0.
> 
> So my question is what does the 16 byte latter half of tsec_keys.bin indicate?
> What does Lockpick do by "tsec_root.find_key(temp_key)"?
> And why my "tsec_keys.bin" doesn't contain extra 16 byte, (i.e why isn't it 48 byte size)

That's true, I appreciate you reading the code. Indeed, in Hekate 4.8 tsec_keys.bin file size changed from 48 to 32 bytes. The last 16 bytes were always 00 so he must've changed it for that reason.

`tsec_root.find_key(temp_key)` checks if the number at offset 0x10 is actually the tsec_root_key, which will only appear on firmware 6.2.0.

**Comment by RKX1209** [comment]
Thanks for responding.
OK. I'll try expand tsec_keys.bin to 48 bytes by adding 16 byte extra 0s manually.

**Comment by shchmue** [comment]
that'll work until I push a fix but the easier way would be to dump keys from biskeydump to SD

**Comment by RKX1209** [comment]
Aha. Thanks!
